name: ieeg
channels:
  - defaults
dependencies:
  - anyio=4.2.0
  - aom=3.6.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.11.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - blosc=1.21.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2023.11.17
  - cffi=1.16.0
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - comm=0.1.2
  - contourpy=1.2.0
  - cryptography=41.0.7
  - cycler=0.11.0
  - cytoolz=0.12.2
  - daal4py=2023.1.1
  - dal=2023.1.1
  - dask-core=2023.11.0
  - dav1d=1.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - executing=0.8.3
  - fonttools=4.25.0
  - freetype=2.12.1
  - fsspec=2023.10.0
  - giflib=5.2.1
  - icc_rt=2022.1.0
  - icu=73.1
  - idna=3.4
  - imagecodecs=2023.1.23
  - imageio=2.31.4
  - importlib-metadata=7.0.1
  - intel-openmp=2023.1.0
  - ipython=8.20.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.8
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lazy_loader=0.3
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.4
  - libavif=0.11.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libpng=1.6.39
  - libpq=12.17
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libzopfli=1.0.3
  - llvmlite=0.41.0
  - locket=1.0.0
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - munkres=1.1.4
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - nest-asyncio=1.5.6
  - networkx=3.1
  - notebook=7.0.6
  - notebook-shim=0.2.3
  - numba=0.58.1
  - numexpr=2.8.7
  - numpy=1.26.3
  - numpy-base=1.26.3
  - openjpeg=2.4.0
  - openssl=3.0.12
  - overrides=7.4.0
  - packaging=23.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.4.1
  - pillow=10.0.1
  - pip=23.3.1
  - platformdirs=3.10.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.11.7
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - pywavelets=1.5.0
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - referencing=0.30.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - scikit-learn-intelex=2023.1.1
  - send2trash=1.8.2
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tbb=2021.8.0
  - terminado=0.17.1
  - threadpoolctl=2.2.0
  - tifffile=2023.4.12
  - tinycss2=1.2.1
  - tk=8.6.12
  - toolz=0.12.0
  - tornado=6.3.3
  - traitlets=5.7.1
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzdata=2023d
  - urllib3=1.26.18
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.41.2
  - xz=5.4.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zfp=1.0.0
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - array-api-compat==1.10.0
      - array-api-extra==0.6.0
      - astor==0.8.1
      - bids==0.0
      - bids-validator==1.14.0
      - bottleneck==1.3.7
      - colorspacious==1.1.2
      - cython==3.0.8
      - darkdetect==0.8.0
      - deepdiff==6.7.1
      - dipy==1.8.0
      - docopt==0.6.2
      - edfio==0.4.3
      - edflib-python==1.0.8
      - formulaic==0.5.2
      - git-filter-repo==2.38.0
      - greenlet==3.0.3
      - h5io==0.2.1
      - h5py==3.10.0
      - ieeg==0.6.0
      - interface-meta==1.3.0
      - ipykernel==6.29.5
      - joblib==1.4.2
      - keras==3.6.0
      - markdown-it-py==3.0.0
      - matplotlib==3.8.2
      - mdurl==0.1.2
      - ml-dtypes==0.5.0
      - mne==1.8.0
      - mne-bids==0.16.0
      - mne-qt-browser==0.6.1
      - namex==0.0.8
      - nibabel==5.2.0
      - num2words==0.5.13
      - optree==0.13.1
      - ordered-set==4.1.0
      - pandas==2.2.0
      - patsy==0.5.6
      - pooch==1.8.0
      - psutil==5.9.8
      - pybids==0.16.4
      - pyqtgraph==0.13.3
      - pytz==2023.4
      - pyvista==0.43.2
      - pyvistaqt==0.11.0
      - qdarkstyle==3.2.3
      - qtpy==2.4.1
      - rich==13.9.4
      - rsatoolbox==0.1.5
      - scikit-image==0.22.0
      - scikit-learn==1.4.0
      - scipy==1.12.0
      - scooby==0.9.2
      - seaborn==0.13.2
      - setuptools-scm==8.0.4
      - sqlalchemy==2.0.25
      - statsmodels==0.14.1
      - tqdm==4.66.1
      - trx-python==0.2.9
      - vtk==9.3.0
      - wrapt==1.16.0
      - xgboost==2.1.2
