"""
Brain Figure — MNE-Python + Glasser HCP-MMP1 Atlas
===================================================
Saves lateral and medial views as separate SVGs.
Highlights dlPFC, ACC, pre-SMA, dmPFC, vmPFC, precuneus, basal ganglia.

Style: Light gray brain with solid, clearly delineated ROI fills.
       Left hemisphere only.

Requirements:
    pip install mne pyvista pyvistaqt matplotlib

Setup:
    Place lh.HCPMMP1.annot and rh.HCPMMP1.annot in:
      <subjects_dir>/fsaverage/label/

Usage:
    python brain_figure_glasser.py
"""

import mne
import numpy as np
import os
import pyvista as pv

mne.viz.set_3d_backend('pyvistaqt')

# =============================================================================
# 1. SETUP
# =============================================================================

fs_dir = mne.datasets.fetch_fsaverage(verbose=True)
subjects_dir = os.path.dirname(fs_dir)

# =============================================================================
# 2. ROI DEFINITIONS — Glasser HCP-MMP1 parcels
# =============================================================================

ROIS = {
    'dlPFC': [
        '46', '9-46d', 'p9-46v', 'a9-46v', '8C', '8Av', '8Ad',
    ],
    'ACC': [
        'p32pr', 'a32pr', 'd32', 'p24', 'a24', '33pr',
    ],
    'preSMA': [
        '6a', 'SCEF',
    ],
    'dmPFC': [
        '8BM', '9m',
    ],
    'vmPFC': [
        '25', 's32', '10v', '10r', 'OFC', 'pOFC',
    ],
    'precuneus': [
        '7m', 'PCV', 'POS2', '31pv', '31pd',
    ],
}

# =============================================================================
# 3. COLOR SCHEME — maximally distinct
# =============================================================================

COLORS = {
    'dlPFC':         '#1F78B4',   # strong blue
    'ACC':           '#E31A1C',   # red
    'preSMA':        '#33A02C',   # green
    'dmPFC':         '#FF7F00',   # orange
    'vmPFC':         '#FFED6F',   # bright yellow
    'precuneus':     '#CB2DB4',   # magenta/purple
    'Basal Ganglia': '#1B9E77',   # teal
}

# =============================================================================
# 4. HELPER: Find Glasser label
# =============================================================================

def find_glasser_label(labels, parcel_name, hemi):
    """Find a Glasser label by parcel name."""
    prefix = 'L' if hemi == 'lh' else 'R'
    target = f'{prefix}_{parcel_name}_ROI-{hemi}'
    label_dict = {l.name: l for l in labels}
    return label_dict.get(target, None)


# =============================================================================
# 5. ADD CORTICAL REGIONS — solid fills, no borders
# =============================================================================

def add_cortical_regions(brain, hemis=None):
    """Add Glasser-based cortical ROIs to the brain as solid opaque fills."""
    if hemis is None:
        hemis = ['lh', 'rh']

    count = 0
    not_found = []

    for hemi in hemis:
        labels = mne.read_labels_from_annot(
            'fsaverage', parc='HCPMMP1',
            subjects_dir=subjects_dir, hemi=hemi
        )

        for roi_name, parcels in ROIS.items():
            color = COLORS[roi_name]
            for parcel in parcels:
                label = find_glasser_label(labels, parcel, hemi)
                if label is not None:
                    brain.add_label(
                        label,
                        color=color,
                        alpha=1.0,
                        borders=False,
                    )
                    count += 1
                else:
                    not_found.append(f"{hemi}: {parcel} ({roi_name})")

    print(f"✓ Added {count} cortical labels")
    if not_found:
        print("⚠ Labels not found:")
        for nf in not_found:
            print(f"  {nf}")


# =============================================================================
# 6. ADD BASAL GANGLIA AS ELLIPSOIDS
# =============================================================================

# Major basal ganglia nuclei, given for the LEFT hemisphere as approximate
# fsaverage surface-RAS (~MNI mm) centers and ellipsoid radii (x, y, z).
# Together these depict the basal ganglia broadly — striatum (caudate +
# putamen), pallidum (GPe + GPi), and STN — rather than centering the STN
# alone. The right hemisphere is generated by mirroring the x coordinate.
# To plot a single undifferentiated blob instead, replace this dict with one
# larger ellipsoid (e.g. center [-18, -2, 2], radii (14, 10, 9)).
BG_NUCLEI = {
    'caudate':  {'center': [-12,  10,   8], 'radii': (5.0, 7.5, 8.0)},
    'putamen':  {'center': [-26,   2,   2], 'radii': (5.0, 9.0, 7.0)},
    'pallidum': {'center': [-18,  -3,  -1], 'radii': (3.5, 6.5, 5.5)},  # GPe + GPi
    'STN':      {'center': [-10, -15,  -5], 'radii': (3.0, 2.5, 2.0)},
}


def add_basal_ganglia(brain, hemis=None, blend=1.35, iso=0.4,
                      resolution=72, smooth_iter=40):
    """Add the basal ganglia as a SINGLE merged, smoothly-blended blob.

    Instead of one ellipsoid per nucleus, this samples a soft (metaball-style)
    scalar field from all nuclei in BG_NUCLEI onto a 3D grid and extracts one
    isosurface, so overlapping nuclei fuse into a single organic shape rather
    than distinct ovals.

    Tuning
    ------
    blend       : how far each nucleus 'reaches' (bigger => more fusion, fatter)
    iso         : isosurface level (lower => fatter/more merged; higher => tighter)
    resolution  : grid points per axis (higher => smoother but slower)
    smooth_iter : Taubin smoothing passes on the final surface
    """
    if hemis is None:
        hemis = ['lh', 'rh']

    plotter = brain._renderer.plotter
    color = COLORS['Basal Ganglia']

    for hemi in hemis:
        sign = -1 if hemi == 'lh' else 1
        centers, radii = [], []
        for spec in BG_NUCLEI.values():
            cx, cy, cz = spec['center']
            centers.append([abs(cx) * sign, cy, cz])
            radii.append(spec['radii'])
        centers = np.asarray(centers, float)
        radii = np.asarray(radii, float) * blend

        # Bounding grid with padding around all nuclei.
        pad = radii.max() + 6.0
        mins = (centers - radii).min(axis=0) - pad
        maxs = (centers + radii).max(axis=0) + pad
        nx = ny = nz = int(resolution)
        xs = np.linspace(mins[0], maxs[0], nx)
        ys = np.linspace(mins[1], maxs[1], ny)
        zs = np.linspace(mins[2], maxs[2], nz)
        X, Y, Z = np.meshgrid(xs, ys, zs, indexing='ij')

        # Soft metaball field: each nucleus is a smooth anisotropic Gaussian;
        # summing them makes nearby nuclei bulge together and fuse.
        field = np.zeros_like(X)
        for (cx, cy, cz), (rx, ry, rz) in zip(centers, radii):
            d2 = ((X - cx) / rx) ** 2 + ((Y - cy) / ry) ** 2 + ((Z - cz) / rz) ** 2
            field += np.exp(-d2)

        spacing = ((maxs[0] - mins[0]) / (nx - 1),
                   (maxs[1] - mins[1]) / (ny - 1),
                   (maxs[2] - mins[2]) / (nz - 1))
        try:
            grid = pv.ImageData(dimensions=(nx, ny, nz),
                                spacing=spacing, origin=tuple(mins))
        except AttributeError:                      # older pyvista
            grid = pv.UniformGrid(dimensions=(nx, ny, nz),
                                  spacing=spacing, origin=tuple(mins))
        grid['field'] = field.ravel(order='F')      # x fastest -> matches grid

        blob = grid.contour([iso], scalars='field')
        if smooth_iter:
            blob = blob.smooth_taubin(n_iter=smooth_iter, pass_band=0.1)

        plotter.add_mesh(blob, color=color, opacity=1.0, smooth_shading=True)
        print(f"✓ Added merged basal ganglia blob ({hemi}): {blob.n_points} pts")

# =============================================================================
# 7. SOFTEN LIGHTING — reduce harsh sulcal shadows
# =============================================================================

def soften_lighting(brain):
    """Boost ambient and reduce specular to make sulci less dark
    and ROI colors more uniform across the surface.
    """
    plotter = brain._renderer.plotter
    renderer = plotter.renderer

    # Adjust all actors: less specular, more ambient
    for actor in renderer.GetActors():
        prop = actor.GetProperty()
        prop.SetSpecular(0.05)      # almost no specular shine
        prop.SetSpecularPower(1.0)
        prop.SetAmbient(0.55)       # higher ambient = less shadow contrast
        prop.SetDiffuse(0.45)       # lower diffuse = softer shading

    print("✓ Softened lighting")


# =============================================================================
# 8. CREATE AND SAVE INDIVIDUAL VIEWS
# =============================================================================

# Cortex transparency: 1.0 = fully opaque (deep structures hidden),
# lower = see-through. ~0.3–0.45 lets the basal ganglia show through
# while the opaque ROI fills stay bold.
BRAIN_ALPHA = 0.4


def make_and_save_view(hemi, view, basename):
    """Create a single brain view and save as both SVG and PNG."""

    cortex_color = 'low_contrast'

    brain = mne.viz.Brain(
        'fsaverage',
        hemi=hemi,
        surf='pial',
        subjects_dir=subjects_dir,
        views=view,
        background='white',
        cortex=cortex_color,
        alpha=BRAIN_ALPHA,        # <-- was 1.0; now see-through so BG is visible
        size=(1200, 1000),
    )

    # Correct transparency sorting for the translucent cortex over the
    # opaque subcortical blobs.
    try:
        brain._renderer.plotter.enable_depth_peeling(number_of_peels=10)
    except Exception as e:
        print(f"⚠ depth peeling unavailable: {e}")

    # Add ROIs as solid fills
    add_cortical_regions(brain, hemis=[hemi])

    # Add basal ganglia ellipsoids
    add_basal_ganglia(brain, hemis=[hemi])

    # Save PNG
    png_path = f'{basename}.png'
    brain.save_image(png_path, mode='rgb')
    print(f"✓ Saved PNG: {png_path}")

    # Save SVG
    svg_path = f'{basename}.svg'
    try:
        plotter = brain._renderer.plotter
        plotter.save_graphic(svg_path)
        print(f"✓ Saved SVG: {svg_path}")
    except Exception as e:
        print(f"⚠ SVG export failed: {e}")
        print("  Try pip install pyvista --upgrade, or use the PNG.")

    brain.close()
    return brain


# =============================================================================
# 9. RUN
# =============================================================================

if __name__ == '__main__':

    # --- Verify labels ---
    print("\n=== Verifying Glasser HCP-MMP1 labels ===")
    labels = mne.read_labels_from_annot(
        'fsaverage', parc='HCPMMP1',
        subjects_dir=subjects_dir, hemi='lh'
    )
    print(f"Total labels loaded: {len(labels)}")

    # =========================================================================
    # Render and save lateral + medial as separate files
    # =========================================================================

    hemi = 'lh'   # change to 'rh' for right hemisphere

    print("\n--- Lateral view ---")
    make_and_save_view(hemi, 'lateral', 'brain_lateral')

    print("\n--- Medial view ---")
    make_and_save_view(hemi, 'medial', 'brain_medial')

    print("\nDone! Files saved:")
    print("  brain_lateral.svg / .png")
    print("  brain_medial.svg / .png")

    # =========================================================================
    # Generate legend as separate SVG
    # =========================================================================

    print("\n--- Generating legend ---")
    import matplotlib.pyplot as plt
    import matplotlib.patches as mpatches

    ROI_LABELS = {
        'dlPFC':         'dlPFC',
        'ACC':           'ACC',
        'preSMA':        'pre-SMA',
        'dmPFC':         'dmPFC',
        'vmPFC':         'vmPFC',
        'precuneus':     'Precuneus',
        'Basal Ganglia': 'Basal Ganglia',
    }

    roi_order = ['dlPFC', 'ACC', 'preSMA', 'dmPFC', 'vmPFC', 'precuneus', 'Basal Ganglia']

    patches = [
        mpatches.Patch(
            facecolor=COLORS[roi_key],
            edgecolor='black',
            linewidth=0.8,
            label=ROI_LABELS[roi_key],
        )
        for roi_key in roi_order
    ]

    # Wide + short figure for a single horizontal row.
    fig, ax = plt.subplots(figsize=(len(patches) * 1.4, 0.6))
    ax.axis('off')

    legend = ax.legend(
        handles=patches,
        loc='center',
        ncol=len(patches),       # <-- one column per entry => single row
        frameon=True,
        framealpha=1.0,
        edgecolor='black',
        fontsize=11,
        handlelength=1.2,
        handleheight=1.2,
        handletextpad=0.5,
        columnspacing=1.2,       # gap between columns
        labelspacing=0.4,
        borderpad=0.6,
    )
    legend.get_frame().set_linewidth(0.8)

    plt.tight_layout()
    plt.savefig('brain_legend_horizontal.svg', format='svg', dpi=300,
                bbox_inches='tight', transparent=True)
    plt.savefig('brain_legend_horizontal.png', dpi=300,
                bbox_inches='tight', transparent=True)
    plt.close()
    print("✓ Saved legend: brain_legend_horizontal.svg / .png")

# =============================================================================
# 10. NOTES
# =============================================================================
"""
CHANGES FROM ORIGINAL
---------------------
1. alpha=1.0 on brain  — fully opaque surface (was 0.15)
2. ROI alpha=1.0       — solid opaque fills (was 0.75)
3. Custom cortex color — light gray with low sulcal contrast
   Format: (gyrus_dark, gyrus_light, sulcus_dark, sulcus_light)
   Increase all 4 values to make the brain lighter overall.
   Decrease the gap between gyrus and sulcus values for less contrast.
4. soften_lighting()   — high ambient, low specular for flatter shading
5. No black borders    — they look too jagged on the pial surface

TUNING THE CORTEX COLOR
------------------------
Valid cortex presets:
  - 'low_contrast'   — (current) light gray, gentle sulcal shading
  - 'bone'           — warm beige/gray
  - 'ivory'          — very light, almost white
  - 'classic'        — darker gray, more contrast
  - 'high_contrast'  — strong sulcal contrast
  - Any color name   — e.g. 'grey', '#B0B0B0' for uniform flat color

TUNING THE LIGHTING
--------------------
In soften_lighting(), adjust:
  - Ambient (currently 0.55): higher = flatter, less shadow
  - Diffuse (currently 0.45): lower = less directional shading
  - Specular (currently 0.05): 0.0 = completely matte

IF ROIs STILL BLEED
--------------------
On pial surfaces, adjacent ROIs can look merged because sulcal
geometry pushes vertices together. Options:
  a) Add borders back with borders=1 (thin) — may still be jagged
  b) Use surf='white' for a smoother surface (less anatomical detail)
  c) Use surf='inflated' (you said you don't want this, but noting it)
  d) Post-process in Illustrator: add thin strokes to ROI paths in SVG

COMPOSITING
-----------
    dlPFC          ■ #2166AC (blue)
    ACC            ■ #D6604D (salmon)
    pre-SMA        ■ #66A61E (green)
    dmPFC          ■ #7570B3 (purple)
    vmPFC          ■ #E6AB02 (gold)
    Precuneus      ■ #E7298A (pink)
    Basal Ganglia  ■ #1B9E77 (teal)

DEPICTING THE BASAL GANGLIA
---------------------------
Figure 2 now shows the basal ganglia broadly (striatum, pallidum, STN) as a
single color/legend group rather than centering the STN, per reviewer request.
- To add/remove nuclei or retune positions, edit BG_NUCLEI (section 6).
- For a single undifferentiated blob, replace BG_NUCLEI with one larger
  ellipsoid (see the comment above the dict).
- For anatomically exact subcortical surfaces instead of schematic ellipsoids,
  use mne.viz.Brain.add_volume_labels(aseg='aseg', labels=['Left-Caudate',
  'Left-Putamen', 'Left-Pallidum', 'Left-Accumbens-area']); this requires an
  aseg.mgz in the subject's mri/ directory (STN is not in the standard aseg).
"""
